// AUTO-GENERATED by scripts/generate-learning-loader.js — do not edit
import type { ModuleNode } from './types'

import * as _ap_ages_basics_study from './aptitude/ages-basics/study'
import * as _ap_ages_basics_exercise from './aptitude/ages-basics/exercise'
import * as _ap_ages_basics_assignment from './aptitude/ages-basics/assignment'
import * as _ap_aptitude_final_study from './aptitude/aptitude-final/study'
import * as _ap_aptitude_final_exercise from './aptitude/aptitude-final/exercise'
import * as _ap_aptitude_final_assignment from './aptitude/aptitude-final/assignment'
import * as _ap_averages_basics_study from './aptitude/averages-basics/study'
import * as _ap_averages_basics_exercise from './aptitude/averages-basics/exercise'
import * as _ap_averages_basics_assignment from './aptitude/averages-basics/assignment'
import * as _ap_ci_study from './aptitude/ci/study'
import * as _ap_ci_exercise from './aptitude/ci/exercise'
import * as _ap_ci_assignment from './aptitude/ci/assignment'
import * as _ap_company_mcq_ns_study from './aptitude/company-mcq-ns/study'
import * as _ap_company_mcq_ns_exercise from './aptitude/company-mcq-ns/exercise'
import * as _ap_company_mcq_ns_assignment from './aptitude/company-mcq-ns/assignment'
import * as _ap_lcm_hcf_apps_study from './aptitude/lcm-hcf-apps/study'
import * as _ap_lcm_hcf_apps_exercise from './aptitude/lcm-hcf-apps/exercise'
import * as _ap_lcm_hcf_apps_assignment from './aptitude/lcm-hcf-apps/assignment'
import * as _ap_lcm_hcf_concepts_study from './aptitude/lcm-hcf-concepts/study'
import * as _ap_lcm_hcf_concepts_exercise from './aptitude/lcm-hcf-concepts/exercise'
import * as _ap_lcm_hcf_concepts_assignment from './aptitude/lcm-hcf-concepts/assignment'
import * as _ap_mixtures_basics_study from './aptitude/mixtures-basics/study'
import * as _ap_mixtures_basics_exercise from './aptitude/mixtures-basics/exercise'
import * as _ap_mixtures_basics_assignment from './aptitude/mixtures-basics/assignment'
import * as _ap_numbers_study from './aptitude/numbers/study'
import * as _ap_numbers_exercise from './aptitude/numbers/exercise'
import * as _ap_numbers_assignment from './aptitude/numbers/assignment'
import * as _ap_partnerships_basics_study from './aptitude/partnerships-basics/study'
import * as _ap_partnerships_basics_exercise from './aptitude/partnerships-basics/exercise'
import * as _ap_partnerships_basics_assignment from './aptitude/partnerships-basics/assignment'
import * as _ap_percentages_basics_study from './aptitude/percentages-basics/study'
import * as _ap_percentages_basics_exercise from './aptitude/percentages-basics/exercise'
import * as _ap_percentages_basics_assignment from './aptitude/percentages-basics/assignment'
import * as _ap_perm_comb_basics_study from './aptitude/perm-comb-basics/study'
import * as _ap_perm_comb_basics_exercise from './aptitude/perm-comb-basics/exercise'
import * as _ap_perm_comb_basics_assignment from './aptitude/perm-comb-basics/assignment'
import * as _ap_powercycles_study from './aptitude/powercycles/study'
import * as _ap_powercycles_exercise from './aptitude/powercycles/exercise'
import * as _ap_powercycles_assignment from './aptitude/powercycles/assignment'
import * as _ap_probability_basics_study from './aptitude/probability-basics/study'
import * as _ap_probability_basics_exercise from './aptitude/probability-basics/exercise'
import * as _ap_probability_basics_assignment from './aptitude/probability-basics/assignment'
import * as _ap_profit_loss_basics_study from './aptitude/profit-loss-basics/study'
import * as _ap_profit_loss_basics_exercise from './aptitude/profit-loss-basics/exercise'
import * as _ap_profit_loss_basics_assignment from './aptitude/profit-loss-basics/assignment'
import * as _ap_ratios_basics_study from './aptitude/ratios-basics/study'
import * as _ap_ratios_basics_exercise from './aptitude/ratios-basics/exercise'
import * as _ap_ratios_basics_assignment from './aptitude/ratios-basics/assignment'
import * as _ap_remainder_cycles_study from './aptitude/remainder-cycles/study'
import * as _ap_remainder_cycles_exercise from './aptitude/remainder-cycles/exercise'
import * as _ap_remainder_cycles_assignment from './aptitude/remainder-cycles/assignment'
import * as _ap_si_study from './aptitude/si/study'
import * as _ap_si_exercise from './aptitude/si/exercise'
import * as _ap_si_assignment from './aptitude/si/assignment'
import * as _ap_time_work_basics_study from './aptitude/time-work-basics/study'
import * as _ap_time_work_basics_exercise from './aptitude/time-work-basics/exercise'
import * as _ap_time_work_basics_assignment from './aptitude/time-work-basics/assignment'
import * as _ap_tsd_basics_study from './aptitude/tsd-basics/study'
import * as _ap_tsd_basics_exercise from './aptitude/tsd-basics/exercise'
import * as _ap_tsd_basics_assignment from './aptitude/tsd-basics/assignment'
import * as _re_blood_basics_study from './reasoning/blood-basics/study'
import * as _re_blood_basics_exercise from './reasoning/blood-basics/exercise'
import * as _re_blood_basics_assignment from './reasoning/blood-basics/assignment'
import * as _re_calendars_basics_study from './reasoning/calendars-basics/study'
import * as _re_calendars_basics_exercise from './reasoning/calendars-basics/exercise'
import * as _re_calendars_basics_assignment from './reasoning/calendars-basics/assignment'
import * as _re_clock_1_study from './reasoning/clock-1/study'
import * as _re_clock_1_exercise from './reasoning/clock-1/exercise'
import * as _re_clock_1_assignment from './reasoning/clock-1/assignment'
import * as _re_clock_2_study from './reasoning/clock-2/study'
import * as _re_clock_2_exercise from './reasoning/clock-2/exercise'
import * as _re_clock_2_assignment from './reasoning/clock-2/assignment'
import * as _re_clock_3_study from './reasoning/clock-3/study'
import * as _re_clock_3_exercise from './reasoning/clock-3/exercise'
import * as _re_clock_3_assignment from './reasoning/clock-3/assignment'
import * as _re_coding_basics_study from './reasoning/coding-basics/study'
import * as _re_coding_basics_exercise from './reasoning/coding-basics/exercise'
import * as _re_coding_basics_assignment from './reasoning/coding-basics/assignment'
import * as _re_company_mcq_clocks_study from './reasoning/company-mcq-clocks/study'
import * as _re_company_mcq_clocks_exercise from './reasoning/company-mcq-clocks/exercise'
import * as _re_company_mcq_clocks_assignment from './reasoning/company-mcq-clocks/assignment'
import * as _re_cubes_basics_study from './reasoning/cubes-basics/study'
import * as _re_cubes_basics_exercise from './reasoning/cubes-basics/exercise'
import * as _re_cubes_basics_assignment from './reasoning/cubes-basics/assignment'
import * as _re_data_arr_basics_study from './reasoning/data-arr-basics/study'
import * as _re_data_arr_basics_exercise from './reasoning/data-arr-basics/exercise'
import * as _re_data_arr_basics_assignment from './reasoning/data-arr-basics/assignment'
import * as _re_di_basics_study from './reasoning/di-basics/study'
import * as _re_di_basics_exercise from './reasoning/di-basics/exercise'
import * as _re_di_basics_assignment from './reasoning/di-basics/assignment'
import * as _re_directions_basics_study from './reasoning/directions-basics/study'
import * as _re_directions_basics_exercise from './reasoning/directions-basics/exercise'
import * as _re_directions_basics_assignment from './reasoning/directions-basics/assignment'
import * as _re_ds_basics_study from './reasoning/ds-basics/study'
import * as _re_ds_basics_exercise from './reasoning/ds-basics/exercise'
import * as _re_ds_basics_assignment from './reasoning/ds-basics/assignment'
import * as _re_puzzles_basics_study from './reasoning/puzzles-basics/study'
import * as _re_puzzles_basics_exercise from './reasoning/puzzles-basics/exercise'
import * as _re_puzzles_basics_assignment from './reasoning/puzzles-basics/assignment'
import * as _re_ranking_basics_study from './reasoning/ranking-basics/study'
import * as _re_ranking_basics_exercise from './reasoning/ranking-basics/exercise'
import * as _re_ranking_basics_assignment from './reasoning/ranking-basics/assignment'
import * as _re_reasoning_final_study from './reasoning/reasoning-final/study'
import * as _re_reasoning_final_exercise from './reasoning/reasoning-final/exercise'
import * as _re_reasoning_final_assignment from './reasoning/reasoning-final/assignment'
import * as _re_syllogisms_basics_study from './reasoning/syllogisms-basics/study'
import * as _re_syllogisms_basics_exercise from './reasoning/syllogisms-basics/exercise'
import * as _re_syllogisms_basics_assignment from './reasoning/syllogisms-basics/assignment'
import * as _re_venn_basics_study from './reasoning/venn-basics/study'
import * as _re_venn_basics_exercise from './reasoning/venn-basics/exercise'
import * as _re_venn_basics_assignment from './reasoning/venn-basics/assignment'
import * as _ve_cloze_basics_study from './verbal/cloze-basics/study'
import * as _ve_cloze_basics_exercise from './verbal/cloze-basics/exercise'
import * as _ve_cloze_basics_assignment from './verbal/cloze-basics/assignment'
import * as _ve_error_basics_study from './verbal/error-basics/study'
import * as _ve_error_basics_exercise from './verbal/error-basics/exercise'
import * as _ve_error_basics_assignment from './verbal/error-basics/assignment'
import * as _ve_fill_basics_study from './verbal/fill-basics/study'
import * as _ve_fill_basics_exercise from './verbal/fill-basics/exercise'
import * as _ve_fill_basics_assignment from './verbal/fill-basics/assignment'
import * as _ve_para_basics_study from './verbal/para-basics/study'
import * as _ve_para_basics_exercise from './verbal/para-basics/exercise'
import * as _ve_para_basics_assignment from './verbal/para-basics/assignment'
import * as _ve_rc_basics_study from './verbal/rc-basics/study'
import * as _ve_rc_basics_exercise from './verbal/rc-basics/exercise'
import * as _ve_rc_basics_assignment from './verbal/rc-basics/assignment'
import * as _ve_sc_basics_study from './verbal/sc-basics/study'
import * as _ve_sc_basics_exercise from './verbal/sc-basics/exercise'
import * as _ve_sc_basics_assignment from './verbal/sc-basics/assignment'
import * as _ve_speech_basics_study from './verbal/speech-basics/study'
import * as _ve_speech_basics_exercise from './verbal/speech-basics/exercise'
import * as _ve_speech_basics_assignment from './verbal/speech-basics/assignment'
import * as _ve_syn_basics_study from './verbal/syn-basics/study'
import * as _ve_syn_basics_exercise from './verbal/syn-basics/exercise'
import * as _ve_syn_basics_assignment from './verbal/syn-basics/assignment'
import * as _ve_verbal_company_mcq_study from './verbal/verbal-company-mcq/study'
import * as _ve_verbal_company_mcq_exercise from './verbal/verbal-company-mcq/exercise'
import * as _ve_verbal_company_mcq_assignment from './verbal/verbal-company-mcq/assignment'
import * as _ve_verbal_final_study from './verbal/verbal-final/study'
import * as _ve_verbal_final_exercise from './verbal/verbal-final/exercise'
import * as _ve_verbal_final_assignment from './verbal/verbal-final/assignment'
import * as _ve_vocab_basics_study from './verbal/vocab-basics/study'
import * as _ve_vocab_basics_exercise from './verbal/vocab-basics/exercise'
import * as _ve_vocab_basics_assignment from './verbal/vocab-basics/assignment'
import * as _ve_voice_basics_study from './verbal/voice-basics/study'
import * as _ve_voice_basics_exercise from './verbal/voice-basics/exercise'
import * as _ve_voice_basics_assignment from './verbal/voice-basics/assignment'
import * as _py_functions_study from './python/functions/study'
import * as _py_functions_exercise from './python/functions/exercise'
import * as _py_functions_assignment from './python/functions/assignment'
import * as _py_intro_python_study from './python/intro-python/study'
import * as _py_intro_python_exercise from './python/intro-python/exercise'
import * as _py_intro_python_assignment from './python/intro-python/assignment'
import * as _py_io_basics_study from './python/io-basics/study'
import * as _py_io_basics_exercise from './python/io-basics/exercise'
import * as _py_io_basics_assignment from './python/io-basics/assignment'
import * as _py_lists_study from './python/lists/study'
import * as _py_lists_exercise from './python/lists/exercise'
import * as _py_lists_assignment from './python/lists/assignment'
import * as _py_loop_control_study from './python/loop-control/study'
import * as _py_loop_control_exercise from './python/loop-control/exercise'
import * as _py_loop_control_assignment from './python/loop-control/assignment'
import * as _py_loops_study from './python/loops/study'
import * as _py_loops_exercise from './python/loops/exercise'
import * as _py_loops_assignment from './python/loops/assignment'
import * as _py_nested_conditions_study from './python/nested-conditions/study'
import * as _py_nested_conditions_exercise from './python/nested-conditions/exercise'
import * as _py_nested_conditions_assignment from './python/nested-conditions/assignment'
import * as _py_operators_conditionals_study from './python/operators-conditionals/study'
import * as _py_operators_conditionals_exercise from './python/operators-conditionals/exercise'
import * as _py_operators_conditionals_assignment from './python/operators-conditionals/assignment'
import * as _py_recursion_study from './python/recursion/study'
import * as _py_recursion_exercise from './python/recursion/exercise'
import * as _py_recursion_assignment from './python/recursion/assignment'
import * as _py_strings_variables_study from './python/strings-variables/study'
import * as _py_strings_variables_exercise from './python/strings-variables/exercise'
import * as _py_strings_variables_assignment from './python/strings-variables/assignment'

const TOPIC_CONFIG = [
  { moduleId: 'aptitude', topicId: 'ages-basics', label: "Ages", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'aptitude-final', label: "Final Assessment", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'averages-basics', label: "Averages", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'ci', label: "Compound Interest", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'company-mcq-ns', label: "Company-Specific MCQs", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'lcm-hcf-apps', label: "LCM & HCF (Applications)", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'lcm-hcf-concepts', label: "LCM & HCF (Concepts)", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'mixtures-basics', label: "Mixtures & Alligations", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'numbers', label: "Numbers", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'partnerships-basics', label: "Partnerships", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'percentages-basics', label: "Percentages", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'perm-comb-basics', label: "Permutations & Combinations", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'powercycles', label: "Power Cycles", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'probability-basics', label: "Probability", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'profit-loss-basics', label: "Profit & Loss", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'ratios-basics', label: "Ratios & Proportions", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'remainder-cycles', label: "Remainder Cycles", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'si', label: "Simple Interest", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'time-work-basics', label: "Time & Work", actions: ["study","exercise","assignment"] },
  { moduleId: 'aptitude', topicId: 'tsd-basics', label: "Time, Speed & Distance", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'blood-basics', label: "Blood Relations", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'calendars-basics', label: "Calendars", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'clock-1', label: "Clock 1", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'clock-2', label: "Clock 2", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'clock-3', label: "Clock 3", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'coding-basics', label: "Coding & Decoding", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'company-mcq-clocks', label: "Company-Specific MCQs", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'cubes-basics', label: "Cubes", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'data-arr-basics', label: "Data Arrangements", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'di-basics', label: "Data Interpretation", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'directions-basics', label: "Directions", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'ds-basics', label: "Data Sufficiency", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'puzzles-basics', label: "Puzzles", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'ranking-basics', label: "Ranking", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'reasoning-final', label: "Final Assessment", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'syllogisms-basics', label: "Syllogisms", actions: ["study","exercise","assignment"] },
  { moduleId: 'reasoning', topicId: 'venn-basics', label: "Venn Diagrams", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'cloze-basics', label: "Cloze Test", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'error-basics', label: "Error Spotting", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'fill-basics', label: "Fill in the Blanks", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'para-basics', label: "Para Jumbles", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'rc-basics', label: "Reading Comprehension", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'sc-basics', label: "Sentence Correction", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'speech-basics', label: "Direct & Indirect Speech", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'syn-basics', label: "Synonyms & Antonyms", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'verbal-company-mcq', label: "Company-Specific MCQs", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'verbal-final', label: "Final Assessment", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'vocab-basics', label: "Vocabulary", actions: ["study","exercise","assignment"] },
  { moduleId: 'verbal', topicId: 'voice-basics', label: "Active & Passive Voice", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'functions', label: "Functions", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'intro-python', label: "Introduction to Python", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'io-basics', label: "I/O Basics", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'lists', label: "Lists", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'loop-control', label: "Loop Control Statements", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'loops', label: "Loops", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'nested-conditions', label: "Nested Conditions", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'operators-conditionals', label: "Operators & Conditional Statements", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'recursion', label: "Recursion", actions: ["study","exercise","assignment"] },
  { moduleId: 'python', topicId: 'strings-variables', label: "Strings & Variables", actions: ["study","exercise","assignment"] },
] as const

function buildModuleTree(moduleId: string, moduleLabel: string): ModuleNode {
  const topics = TOPIC_CONFIG.filter((c) => c.moduleId === moduleId)
  const children: ModuleNode[] = topics.map((t) => ({
    id: t.topicId,
    label: t.label,
    children: t.actions.map((a) => {
      const id = `${t.topicId}-${a}`
      const meta = a === 'study' ? undefined : a === 'exercise' ? '10 Questions' : a === 'assignment' ? '20 MCQs' : '2 Questions'
      const label = a === 'study' ? 'Study Material' : a === 'exercise' ? 'Basic Exercise (10 Questions)' : a === 'assignment' ? 'Assignment (20 MCQs)' : 'Coding Practice (2 Questions – Interview POV)'
      return { id, label, type: a as ModuleNode['type'], meta }
    }),
  }))
  return { id: moduleId, label: moduleLabel, children }
}

export const aptitudeModule = buildModuleTree('aptitude', 'Quantitative Aptitude')
export const reasoningModule = buildModuleTree('reasoning', 'Logical Reasoning')
export const verbalModule = buildModuleTree('verbal', 'Verbal Ability')
export const pythonModule = buildModuleTree('python', 'Python Programming')

export function getLearningModules(): { aptitude: ModuleNode; reasoning: ModuleNode; verbal: ModuleNode; python: ModuleNode } {
  return { aptitude: aptitudeModule, reasoning: reasoningModule, verbal: verbalModule, python: pythonModule }
}

export const studyContentMap: Record<string, any> = {
  'ages-basics-study': Object.values(_ap_ages_basics_study)[0],
  'aptitude-final-study': Object.values(_ap_aptitude_final_study)[0],
  'averages-basics-study': Object.values(_ap_averages_basics_study)[0],
  'ci-study': Object.values(_ap_ci_study)[0],
  'company-mcq-ns-study': Object.values(_ap_company_mcq_ns_study)[0],
  'lcm-hcf-apps-study': Object.values(_ap_lcm_hcf_apps_study)[0],
  'lcm-hcf-concepts-study': Object.values(_ap_lcm_hcf_concepts_study)[0],
  'mixtures-basics-study': Object.values(_ap_mixtures_basics_study)[0],
  'numbers-study': Object.values(_ap_numbers_study)[0],
  'partnerships-basics-study': Object.values(_ap_partnerships_basics_study)[0],
  'percentages-basics-study': Object.values(_ap_percentages_basics_study)[0],
  'perm-comb-basics-study': Object.values(_ap_perm_comb_basics_study)[0],
  'powercycles-study': Object.values(_ap_powercycles_study)[0],
  'probability-basics-study': Object.values(_ap_probability_basics_study)[0],
  'profit-loss-basics-study': Object.values(_ap_profit_loss_basics_study)[0],
  'ratios-basics-study': Object.values(_ap_ratios_basics_study)[0],
  'remainder-cycles-study': Object.values(_ap_remainder_cycles_study)[0],
  'si-study': Object.values(_ap_si_study)[0],
  'time-work-basics-study': Object.values(_ap_time_work_basics_study)[0],
  'tsd-basics-study': Object.values(_ap_tsd_basics_study)[0],
  'blood-basics-study': Object.values(_re_blood_basics_study)[0],
  'calendars-basics-study': Object.values(_re_calendars_basics_study)[0],
  'clock-1-study': Object.values(_re_clock_1_study)[0],
  'clock-2-study': Object.values(_re_clock_2_study)[0],
  'clock-3-study': Object.values(_re_clock_3_study)[0],
  'coding-basics-study': Object.values(_re_coding_basics_study)[0],
  'company-mcq-clocks-study': Object.values(_re_company_mcq_clocks_study)[0],
  'cubes-basics-study': Object.values(_re_cubes_basics_study)[0],
  'data-arr-basics-study': Object.values(_re_data_arr_basics_study)[0],
  'di-basics-study': Object.values(_re_di_basics_study)[0],
  'directions-basics-study': Object.values(_re_directions_basics_study)[0],
  'ds-basics-study': Object.values(_re_ds_basics_study)[0],
  'puzzles-basics-study': Object.values(_re_puzzles_basics_study)[0],
  'ranking-basics-study': Object.values(_re_ranking_basics_study)[0],
  'reasoning-final-study': Object.values(_re_reasoning_final_study)[0],
  'syllogisms-basics-study': Object.values(_re_syllogisms_basics_study)[0],
  'venn-basics-study': Object.values(_re_venn_basics_study)[0],
  'cloze-basics-study': Object.values(_ve_cloze_basics_study)[0],
  'error-basics-study': Object.values(_ve_error_basics_study)[0],
  'fill-basics-study': Object.values(_ve_fill_basics_study)[0],
  'para-basics-study': Object.values(_ve_para_basics_study)[0],
  'rc-basics-study': Object.values(_ve_rc_basics_study)[0],
  'sc-basics-study': Object.values(_ve_sc_basics_study)[0],
  'speech-basics-study': Object.values(_ve_speech_basics_study)[0],
  'syn-basics-study': Object.values(_ve_syn_basics_study)[0],
  'verbal-company-mcq-study': Object.values(_ve_verbal_company_mcq_study)[0],
  'verbal-final-study': Object.values(_ve_verbal_final_study)[0],
  'vocab-basics-study': Object.values(_ve_vocab_basics_study)[0],
  'voice-basics-study': Object.values(_ve_voice_basics_study)[0],
  'functions-study': Object.values(_py_functions_study)[0],
  'intro-python-study': Object.values(_py_intro_python_study)[0],
  'io-basics-study': Object.values(_py_io_basics_study)[0],
  'lists-study': Object.values(_py_lists_study)[0],
  'loop-control-study': Object.values(_py_loop_control_study)[0],
  'loops-study': Object.values(_py_loops_study)[0],
  'nested-conditions-study': Object.values(_py_nested_conditions_study)[0],
  'operators-conditionals-study': Object.values(_py_operators_conditionals_study)[0],
  'recursion-study': Object.values(_py_recursion_study)[0],
  'strings-variables-study': Object.values(_py_strings_variables_study)[0],
}

export const exerciseContentMap: Record<string, any> = {
  'ages-basics-exercise': Object.values(_ap_ages_basics_exercise)[0],
  'aptitude-final-exercise': Object.values(_ap_aptitude_final_exercise)[0],
  'averages-basics-exercise': Object.values(_ap_averages_basics_exercise)[0],
  'ci-exercise': Object.values(_ap_ci_exercise)[0],
  'company-mcq-ns-exercise': Object.values(_ap_company_mcq_ns_exercise)[0],
  'lcm-hcf-apps-exercise': Object.values(_ap_lcm_hcf_apps_exercise)[0],
  'lcm-hcf-concepts-exercise': Object.values(_ap_lcm_hcf_concepts_exercise)[0],
  'mixtures-basics-exercise': Object.values(_ap_mixtures_basics_exercise)[0],
  'numbers-exercise': Object.values(_ap_numbers_exercise)[0],
  'partnerships-basics-exercise': Object.values(_ap_partnerships_basics_exercise)[0],
  'percentages-basics-exercise': Object.values(_ap_percentages_basics_exercise)[0],
  'perm-comb-basics-exercise': Object.values(_ap_perm_comb_basics_exercise)[0],
  'powercycles-exercise': Object.values(_ap_powercycles_exercise)[0],
  'probability-basics-exercise': Object.values(_ap_probability_basics_exercise)[0],
  'profit-loss-basics-exercise': Object.values(_ap_profit_loss_basics_exercise)[0],
  'ratios-basics-exercise': Object.values(_ap_ratios_basics_exercise)[0],
  'remainder-cycles-exercise': Object.values(_ap_remainder_cycles_exercise)[0],
  'si-exercise': Object.values(_ap_si_exercise)[0],
  'time-work-basics-exercise': Object.values(_ap_time_work_basics_exercise)[0],
  'tsd-basics-exercise': Object.values(_ap_tsd_basics_exercise)[0],
  'blood-basics-exercise': Object.values(_re_blood_basics_exercise)[0],
  'calendars-basics-exercise': Object.values(_re_calendars_basics_exercise)[0],
  'clock-1-exercise': Object.values(_re_clock_1_exercise)[0],
  'clock-2-exercise': Object.values(_re_clock_2_exercise)[0],
  'clock-3-exercise': Object.values(_re_clock_3_exercise)[0],
  'coding-basics-exercise': Object.values(_re_coding_basics_exercise)[0],
  'company-mcq-clocks-exercise': Object.values(_re_company_mcq_clocks_exercise)[0],
  'cubes-basics-exercise': Object.values(_re_cubes_basics_exercise)[0],
  'data-arr-basics-exercise': Object.values(_re_data_arr_basics_exercise)[0],
  'di-basics-exercise': Object.values(_re_di_basics_exercise)[0],
  'directions-basics-exercise': Object.values(_re_directions_basics_exercise)[0],
  'ds-basics-exercise': Object.values(_re_ds_basics_exercise)[0],
  'puzzles-basics-exercise': Object.values(_re_puzzles_basics_exercise)[0],
  'ranking-basics-exercise': Object.values(_re_ranking_basics_exercise)[0],
  'reasoning-final-exercise': Object.values(_re_reasoning_final_exercise)[0],
  'syllogisms-basics-exercise': Object.values(_re_syllogisms_basics_exercise)[0],
  'venn-basics-exercise': Object.values(_re_venn_basics_exercise)[0],
  'cloze-basics-exercise': Object.values(_ve_cloze_basics_exercise)[0],
  'error-basics-exercise': Object.values(_ve_error_basics_exercise)[0],
  'fill-basics-exercise': Object.values(_ve_fill_basics_exercise)[0],
  'para-basics-exercise': Object.values(_ve_para_basics_exercise)[0],
  'rc-basics-exercise': Object.values(_ve_rc_basics_exercise)[0],
  'sc-basics-exercise': Object.values(_ve_sc_basics_exercise)[0],
  'speech-basics-exercise': Object.values(_ve_speech_basics_exercise)[0],
  'syn-basics-exercise': Object.values(_ve_syn_basics_exercise)[0],
  'verbal-company-mcq-exercise': Object.values(_ve_verbal_company_mcq_exercise)[0],
  'verbal-final-exercise': Object.values(_ve_verbal_final_exercise)[0],
  'vocab-basics-exercise': Object.values(_ve_vocab_basics_exercise)[0],
  'voice-basics-exercise': Object.values(_ve_voice_basics_exercise)[0],
  'functions-exercise': Object.values(_py_functions_exercise)[0],
  'intro-python-exercise': Object.values(_py_intro_python_exercise)[0],
  'io-basics-exercise': Object.values(_py_io_basics_exercise)[0],
  'lists-exercise': Object.values(_py_lists_exercise)[0],
  'loop-control-exercise': Object.values(_py_loop_control_exercise)[0],
  'loops-exercise': Object.values(_py_loops_exercise)[0],
  'nested-conditions-exercise': Object.values(_py_nested_conditions_exercise)[0],
  'operators-conditionals-exercise': Object.values(_py_operators_conditionals_exercise)[0],
  'recursion-exercise': Object.values(_py_recursion_exercise)[0],
  'strings-variables-exercise': Object.values(_py_strings_variables_exercise)[0],
}

export const assignmentContentMap: Record<string, any> = {
  'ages-basics-assignment': Object.values(_ap_ages_basics_assignment)[0],
  'aptitude-final-assignment': Object.values(_ap_aptitude_final_assignment)[0],
  'averages-basics-assignment': Object.values(_ap_averages_basics_assignment)[0],
  'ci-assignment': Object.values(_ap_ci_assignment)[0],
  'company-mcq-ns-assignment': Object.values(_ap_company_mcq_ns_assignment)[0],
  'lcm-hcf-apps-assignment': Object.values(_ap_lcm_hcf_apps_assignment)[0],
  'lcm-hcf-concepts-assignment': Object.values(_ap_lcm_hcf_concepts_assignment)[0],
  'mixtures-basics-assignment': Object.values(_ap_mixtures_basics_assignment)[0],
  'numbers-assignment': Object.values(_ap_numbers_assignment)[0],
  'partnerships-basics-assignment': Object.values(_ap_partnerships_basics_assignment)[0],
  'percentages-basics-assignment': Object.values(_ap_percentages_basics_assignment)[0],
  'perm-comb-basics-assignment': Object.values(_ap_perm_comb_basics_assignment)[0],
  'powercycles-assignment': Object.values(_ap_powercycles_assignment)[0],
  'probability-basics-assignment': Object.values(_ap_probability_basics_assignment)[0],
  'profit-loss-basics-assignment': Object.values(_ap_profit_loss_basics_assignment)[0],
  'ratios-basics-assignment': Object.values(_ap_ratios_basics_assignment)[0],
  'remainder-cycles-assignment': Object.values(_ap_remainder_cycles_assignment)[0],
  'si-assignment': Object.values(_ap_si_assignment)[0],
  'time-work-basics-assignment': Object.values(_ap_time_work_basics_assignment)[0],
  'tsd-basics-assignment': Object.values(_ap_tsd_basics_assignment)[0],
  'blood-basics-assignment': Object.values(_re_blood_basics_assignment)[0],
  'calendars-basics-assignment': Object.values(_re_calendars_basics_assignment)[0],
  'clock-1-assignment': Object.values(_re_clock_1_assignment)[0],
  'clock-2-assignment': Object.values(_re_clock_2_assignment)[0],
  'clock-3-assignment': Object.values(_re_clock_3_assignment)[0],
  'coding-basics-assignment': Object.values(_re_coding_basics_assignment)[0],
  'company-mcq-clocks-assignment': Object.values(_re_company_mcq_clocks_assignment)[0],
  'cubes-basics-assignment': Object.values(_re_cubes_basics_assignment)[0],
  'data-arr-basics-assignment': Object.values(_re_data_arr_basics_assignment)[0],
  'di-basics-assignment': Object.values(_re_di_basics_assignment)[0],
  'directions-basics-assignment': Object.values(_re_directions_basics_assignment)[0],
  'ds-basics-assignment': Object.values(_re_ds_basics_assignment)[0],
  'puzzles-basics-assignment': Object.values(_re_puzzles_basics_assignment)[0],
  'ranking-basics-assignment': Object.values(_re_ranking_basics_assignment)[0],
  'reasoning-final-assignment': Object.values(_re_reasoning_final_assignment)[0],
  'syllogisms-basics-assignment': Object.values(_re_syllogisms_basics_assignment)[0],
  'venn-basics-assignment': Object.values(_re_venn_basics_assignment)[0],
  'cloze-basics-assignment': Object.values(_ve_cloze_basics_assignment)[0],
  'error-basics-assignment': Object.values(_ve_error_basics_assignment)[0],
  'fill-basics-assignment': Object.values(_ve_fill_basics_assignment)[0],
  'para-basics-assignment': Object.values(_ve_para_basics_assignment)[0],
  'rc-basics-assignment': Object.values(_ve_rc_basics_assignment)[0],
  'sc-basics-assignment': Object.values(_ve_sc_basics_assignment)[0],
  'speech-basics-assignment': Object.values(_ve_speech_basics_assignment)[0],
  'syn-basics-assignment': Object.values(_ve_syn_basics_assignment)[0],
  'verbal-company-mcq-assignment': Object.values(_ve_verbal_company_mcq_assignment)[0],
  'verbal-final-assignment': Object.values(_ve_verbal_final_assignment)[0],
  'vocab-basics-assignment': Object.values(_ve_vocab_basics_assignment)[0],
  'voice-basics-assignment': Object.values(_ve_voice_basics_assignment)[0],
  'functions-assignment': Object.values(_py_functions_assignment)[0],
  'intro-python-assignment': Object.values(_py_intro_python_assignment)[0],
  'io-basics-assignment': Object.values(_py_io_basics_assignment)[0],
  'lists-assignment': Object.values(_py_lists_assignment)[0],
  'loop-control-assignment': Object.values(_py_loop_control_assignment)[0],
  'loops-assignment': Object.values(_py_loops_assignment)[0],
  'nested-conditions-assignment': Object.values(_py_nested_conditions_assignment)[0],
  'operators-conditionals-assignment': Object.values(_py_operators_conditionals_assignment)[0],
  'recursion-assignment': Object.values(_py_recursion_assignment)[0],
  'strings-variables-assignment': Object.values(_py_strings_variables_assignment)[0],
}
